### ISSUE TITLE
COI message SHOULD contain a References.

### ISSUE THREAD

**Issue by zvasilev** [coi-dev/coi-specs#2]
If an client  app sync last (n) messages , is better just to refer to the last know message?
The server has full thread info , so could add that info on behalf of the client and capability "ENABLE COI" is enabled ?

**Comment by robert-virkus** [comment]
within the `References` header of an answered message the client can always get the first "root" message of a chat / thread, even when that particular message has not been synchronized before. 

In regards to the last known message you are right, the client should add the ID of the last known message in the `References` field, too.
